# JFLAGS = -g
# JC = javac
# .SUFFIXES: .java .class
# .java.class:
# 	javac $(JFLAGS) $*.java

# CLASSES = \
# 	Foo.java \
# 	Blah.java \
# 	Library.java \
# 	Main.java 

# default: classes

# classes: $(CLASSES:.java=.class)

# clean:
# 	rm *.class
all:
	javac -d bin src/com/ebgf/TGVOverUDP/*.java


# executer
# 	java -cp bin com.gforien.PacMan.Jeu
# faire une archive jar
# 	cd bin
# 	jar -cfe archive.jar com.gforien.PacMan.Jeu com/ resources/
# 	java -jar archive.jar